$(BUILDDIR)/attr.o: attr.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/decl.o: decl.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/driver.o: driver.c config.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/eval.o: eval.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/expr.o: expr.c cc.h null.h utf.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/init.o: init.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/main.o: main.c arg.h cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/map.o: map.c null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/pp.o: pp.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/qbe.o: qbe.c cc.h null.h ops.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/scan.o: scan.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/scope.o: scope.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/stmt.o: stmt.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/targ.o: targ.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/token.o: token.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/tree.o: tree.c null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/type.o: type.c cc.h null.h util.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/utf.o: utf.c null.h utf.h $(BUILDDIR)/marker; $(C)
$(BUILDDIR)/util.o: util.c null.h util.h $(BUILDDIR)/marker; $(C)
